# Generated by Django 3.0 on 2022-04-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20220419_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='isText',
        ),
        migrations.AddField(
            model_name='answer',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='qtype',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(default='', max_length=250),
        ),
    ]
