# Generated by Django 3.0 on 2022-04-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20220419_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
