# Generated by Django 3.0.7 on 2020-06-29 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200627_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='people',
        ),
        migrations.CreateModel(
            name='PanelMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Panel')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person')),
            ],
        ),
        migrations.CreateModel(
            name='OrgsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('last_modified', models.DateField(auto_now=True)),
                ('chair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chair', to='main.Person')),
                ('pastchair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pastchair', to='main.Person')),
                ('vicechair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vicechair', to='main.Person')),
            ],
        ),
        migrations.CreateModel(
            name='MemberAtLarge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OrgsList')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('careerstage', models.PositiveIntegerField(choices=[(0, 'Undergrad'), (1, 'Graduate'), (2, 'Postdoc'), (3, 'Early career')], default=1)),
                ('duedate', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('howtoapply', models.URLField(blank=True, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Person')),
            ],
        ),
    ]
