# Generated by Django 3.0.7 on 2020-07-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_htmlblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
