# Generated by Django 3.0.7 on 2020-07-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200702_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
