# Generated by Django 3.0.7 on 2020-07-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_htmlblock_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
