# Generated by Django 3.0.7 on 2020-07-12 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200704_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentday',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='townhall',
            name='conference',
        ),
        migrations.AddField(
            model_name='conference',
            name='studentday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.StudentDay'),
        ),
        migrations.AddField(
            model_name='conference',
            name='townhall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.TownHall'),
        ),
    ]
