# Generated by Django 3.0.7 on 2020-07-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200712_0611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conference',
            new_name='Meeting',
        ),
    ]
