# Generated by Django 3.0.7 on 2020-07-18 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200713_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelmember',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.Panel'),
        ),
    ]
