# Generated by Django 3.0.7 on 2020-07-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200718_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
